## 🧹 Data Cleaning Process Flowchart

| Step | Action | Description |
| :---: | :--- | :--- |
| **01** | **Read & Load Data** | Load raw dataset into memory using standard encoding. |
| **02** | **Inspect Shape & Nulls** | Check dataset size, column data types, and null value counts. |
| **03** | **Drop Unnecessary Columns** | Remove unused or empty metadata columns (e.g., `Unnamed: 2, 3, 4`). |
| **04** | **Target Encoding** | Convert categorical target classes into numeric format. | 
| **05** | **Handle Missing Values** | Impute or remove missing values in critical features. |
| **06** | **Remove Duplicates** | Eliminate duplicate rows to prevent data leakage in modeling. |

### Step 1: Read and Load Data

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/spam.csv", encoding="latin-1")

In [4]:
df.sample()

       v1                    v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
2724  ham  Nope... C Ì_ then...        NaN        NaN        NaN

### Step 2: Inspect Shape and Null value's

In [5]:
df.shape

(5572, 5)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 677.1 KB

In [7]:
df.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

### Step 3: Drop Unnecessary Column's

| Column | Missing Value (%) |
| :--- | :--- |
| Unnamed: 2 | 99.10| 
| Unnamed: 3 | 99.78|
| Unnamed: 4 | 99.89|

In [8]:
df.drop(columns= ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace= True)

In [10]:
# changing the input and target column names
df.rename(columns={
  "v1": "target",
  "v2": "text",
}, inplace= True)

In [11]:
df.sample()

     target                                            text
4939    ham  ÌÏ go home liao? Ask dad to pick me up at 6...

### Step 4: Categorical Encoding

---

#### 💡 What is Encoding?
Encoding is the process of converting categorical text data into numerical values so that machine learning algorithms can process and learn from the dataset.

---

#### 📌 Common Encoding Techniques

##### 1. One-Hot Encoding
Creates a new binary column (`0` or `1`) for each unique category.
* **Example:**
  | Input Category | Red | Blue | Green |
  | :--- | :---: | :---: | :---: |
  | **Red** | 1 | 0 | 0 |
  | **Blue** | 0 | 1 | 0 |
  | **Green** | 0 | 0 | 1 |

##### 2. Ordinal Encoding
Assigns ordered numeric values (e.g., 1, 2, 3) based on a logical rank or hierarchy.
* **Example:** `Difficulty = ['low', 'medium', 'high']`
  * `High` → 1
  * `Medium` → 2
  * `Low` → 3

##### 3. Label Encoding
Assigns a unique integer identifier to each unique category.
> **Note:** Primarily applied to **target columns** in classification problems.
* **Example:** `Difficulty = ['low', 'medium', 'high']`
  * `High` → 0
  * `Medium` → 1
  * `Low` → 2

---

#### 🎯 Strategy for Our Model
We will use **Label Encoding** to transform our target column:
* `ham` → `0`
* `spam` → `1`

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [14]:
df["target"] = le.fit_transform(df["target"])

In [15]:
le.classes_

array(['ham', 'spam'], dtype=object)

In [20]:
# ham -> 0, spam -> 1
df.sample(5)

      target                                               text
419        1  Send a logo 2 ur lover - 2 names joined by a h...
1184       0               Yo, you around? Just got my car back
5444       0  Good morning. At the repair shop--the ONLY rea...
3141       0  Not planned yet :)going to join company on jan...
4813       0  Ummmmmaah Many many happy returns of d day my ...