## 🧹 Data Cleaning Process Flowchart

| Step | Action | Description |
| :---: | :--- | :--- |
| **01** | **Read & Load Data** | Load raw dataset into memory using standard encoding. |
| **02** | **Inspect Shape & Nulls** | Check dataset size, column data types, and null value counts. |
| **03** | **Drop Unnecessary Columns** | Remove unused or empty metadata columns (e.g., `Unnamed: 2, 3, 4`). |
| **04** | **Target Encoding** | Convert categorical target classes into numeric format. | 
| **05** | **Handle Missing Values** | Impute or remove missing values in critical features. |
| **06** | **Remove Duplicates** | Eliminate duplicate rows to prevent data leakage in modeling. |

### Step 1: Read and Load Data

In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv("../data/raw/spam.csv", encoding="latin-1")

In [29]:
df.sample()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
2187,ham,Oh god. I'm gonna Google nearby cliffs now.,NaN,NaN,NaN

### Step 2: Inspect Shape and Null value's

In [30]:
df.shape

(5572, 5)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 677.1 KB

In [32]:
df.isna().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

### Step 3: Drop Unnecessary Column's

| Column | Missing Value (%) |
| :--- | :--- |
| Unnamed: 2 | 99.10| 
| Unnamed: 3 | 99.78|
| Unnamed: 4 | 99.89|

In [33]:
df.drop(columns= ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace= True)

In [34]:
# changing the input and target column names
df.rename(columns={
  "v1": "target",
  "v2": "text",
}, inplace= True)

In [35]:
df.sample()

     target                                               text
2312   spam  tddnewsletter@emc1.co.uk (More games from TheD...

### Step 4: Categorical Encoding

---

#### 💡 What is Encoding?
Encoding is the process of converting categorical text data into numerical values so that machine learning algorithms can process and learn from the dataset.

---

#### 📌 Common Encoding Techniques

##### 1. One-Hot Encoding
Creates a new binary column (`0` or `1`) for each unique category.
* **Example:**
  | Input Category | Red | Blue | Green |
  | :--- | :---: | :---: | :---: |
  | **Red** | 1 | 0 | 0 |
  | **Blue** | 0 | 1 | 0 |
  | **Green** | 0 | 0 | 1 |

##### 2. Ordinal Encoding
Assigns ordered numeric values (e.g., 1, 2, 3) based on a logical rank or hierarchy.
* **Example:** `Difficulty = ['low', 'medium', 'high']`
  * `High` → 1
  * `Medium` → 2
  * `Low` → 3

##### 3. Label Encoding
Assigns a unique integer identifier to each unique category.
> **Note:** Primarily applied to **target columns** in classification problems.
* **Example:** `Difficulty = ['low', 'medium', 'high']`
  * `High` → 0
  * `Medium` → 1
  * `Low` → 2

---

#### 🎯 Strategy for Our Model
We will use **Label Encoding** to transform our target column:
* `ham` → `0`
* `spam` → `1`

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [37]:
df["target"] = le.fit_transform(df["target"])

In [38]:
le.classes_

array(['ham', 'spam'], dtype=object)

In [39]:
# ham -> 0, spam -> 1
df.sample(5)

      target                                               text
4217       0  Actually i'm waiting for 2 weeks when they sta...
4019       0                 University of southern california.
1545       0  Good afternoon, my love ! Any job prospects ? ...
3876       0  Sorry sir, i will call you tomorrow.  senthil....
904        0  We're all getting worried over here, derek and...

### Step 5: Handling Missing Values

In [40]:
df.isna().sum()

target    0
text      0
dtype: int64

### Step 6: Remove Duplicates

In [41]:
df.duplicated().sum()

np.int64(403)

In [42]:
df.drop_duplicates(keep= "first", inplace= True)

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df.shape

(5169, 2)

In [45]:
df.sample()

     target                                               text
271       0  Night has ended for another day, morning has c...

### Saving the dataset

In [46]:
df.to_csv("../data/cleaned/cleaned.csv", index= False)