In [26]:
import pandas as pd
import numpy as np

In [27]:
spam = pd.read_csv("../data/cleaned/spam.csv")
spam.sample(5)

,target,text,count_alphabet,count_words,count_sent,preprocessed_text
379,0,Customer place i will call you.,31,7,1,custom place call
2405,0,U wake up already? Wat u doing? U picking us u...,150,40,6,u wake alreadi wat u u pick us later rite take...
2326,1,Valentines Day Special! Win over å£1000 in our...,158,31,5,valentin day special win quiz take partner tri...
2564,0,I got a call from a landline number. . . I am ...,106,28,7,got call landlin number ask come anna nagar go...
1167,0,Otherwise had part time job na-tuition..,40,7,1,otherwis part time job

In [28]:
print("Null count: ", spam["preprocessed_text"].isna().sum())
spam.dropna(inplace= True)
print(spam.isna().sum(), spam.shape)

Null count:  9
target               0
text                 0
count_alphabet       0
count_words          0
count_sent           0
preprocessed_text    0
dtype: int64 (5160, 6)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split

In [30]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [31]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()
lr = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
svc = SVC()
rf = RandomForestClassifier(n_estimators=50, random_state=2, n_jobs=-1)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2, n_jobs= -1)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2, n_jobs=-1)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)

In [32]:
models = {
  gnb: "Gaussian Naive Bayes",
  mnb: "Mutinomial Naive Bayes",
  bnb: "Bernoulli Naive Bayes",
  lr : "Logistic Regression",
  knn : "K Neighbors Classifier",
  dt : "Decision Tree Classifier",
  rf : "Random Forest Classifier",
  svc : "Support Vector Classifier",
  abc : "Ada Boost Classifier",
  bc : "Bagging Classifier",
  etc : "Extra Trees Classifier",
  gbdt : "Gradient Boosting Classifier",
}

models

{GaussianNB(): 'Gaussian Naive Bayes',
 MultinomialNB(): 'Mutinomial Naive Bayes',
 BernoulliNB(): 'Bernoulli Naive Bayes',
 LogisticRegression(): 'Logistic Regression',
 KNeighborsClassifier(): 'K Neighbors Classifier',
 DecisionTreeClassifier(): 'Decision Tree Classifier',
 RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=2): 'Random Forest Classifier',
 SVC(): 'Support Vector Classifier',
 AdaBoostClassifier(random_state=2): 'Ada Boost Classifier',
 BaggingClassifier(n_estimators=50, n_jobs=-1, random_state=2): 'Bagging Classifier',
 ExtraTreesClassifier(n_estimators=50, n_jobs=-1, random_state=2): 'Extra Trees Classifier',
 GradientBoostingClassifier(n_estimators=50, random_state=2): 'Gradient Boosting Classifier'}

In [33]:
from typing import Dict

def train_model(models: Dict[object, str], vectorizer: str = "count") -> pd.DataFrame:

  if vectorizer == "tfidf":
    tfidf = TfidfVectorizer(max_features= 5000, stop_words="english")
    X = tfidf.fit_transform(spam["preprocessed_text"]).toarray()
    y = spam["target"]

  else:
    cv = CountVectorizer(max_features=5000)
    X = cv.fit_transform(spam["preprocessed_text"]).toarray()
    y = spam["target"]

  X_train, X_test, y_trian, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  data = {
    "Model": [],
    f"Accuracy {vectorizer}": [],
    f"Precision {vectorizer}": [],
  }

  for model in list(models.keys()):
    print(f"Training model: {models.get(model)}")
    m = model.fit(X_train, y_trian)
    y_pred = model.predict(X_test)

    data["Model"].append(models.get(model))
    data[f"Accuracy {vectorizer}"].append(accuracy_score(y_test, y_pred))
    data[f"Precision {vectorizer}"].append(precision_score(y_test, y_pred))

  return pd.DataFrame(data)

In [34]:
df1 = train_model(models)

Training model: Gaussian Naive Bayes
Training model: Mutinomial Naive Bayes
Training model: Bernoulli Naive Bayes
Training model: Logistic Regression
Training model: K Neighbors Classifier
Training model: Decision Tree Classifier
Training model: Random Forest Classifier
Training model: Support Vector Classifier
Training model: Ada Boost Classifier
Training model: Bagging Classifier
Training model: Extra Trees Classifier
Training model: Gradient Boosting Classifier

In [35]:
df2 = train_model(models, vectorizer="tfidf")

Training model: Gaussian Naive Bayes
Training model: Mutinomial Naive Bayes
Training model: Bernoulli Naive Bayes
Training model: Logistic Regression
Training model: K Neighbors Classifier
Training model: Decision Tree Classifier
Training model: Random Forest Classifier
Training model: Support Vector Classifier
Training model: Ada Boost Classifier
Training model: Bagging Classifier
Training model: Extra Trees Classifier
Training model: Gradient Boosting Classifier

In [36]:
df1.merge(df2, on="Model")

,Model,Accuracy count,Precision count,Accuracy tfidf,Precision tfidf
0,Gaussian Naive Bayes,0.862403,0.457014,0.847868,0.425439
1,Mutinomial Naive Bayes,0.970930,0.866142,0.965116,1.000000
2,Bernoulli Naive Bayes,0.965116,0.957895,0.964147,0.957447
3,Logistic Regression,0.973837,0.980000,0.951550,0.962025
4,K Neighbors Classifier,0.926357,1.000000,0.918605,1.000000
5,Decision Tree Classifier,0.962209,0.868421,0.952519,0.789062
6,Random Forest Classifier,0.974806,1.000000,0.973837,0.980000
7,Support Vector Classifier,0.972868,0.979798,0.971899,0.989583
8,Ada Boost Classifier,0.922481,0.852459,0.915698,0.928571
9,Bagging Classifier,0.968023,0.916667,0.963178,0.869565
10,Extra Trees Classifier,0.970930,0.979381,0.969961,0.979167
11,Gradient Boosting Classifier,0.954457,0.941860,0.950581,0.950000